/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.mycompany.mavenproject1;

/**
 *
 * @author astr4
 */
public class Bolum extends javax.swing.JFrame {

    /** Creates new form App2 */
    public Bolum() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fizyolojiButton = new javax.swing.JButton();
        norolojıButton = new javax.swing.JButton();
        gozButton = new javax.swing.JButton();
        urolojıButton = new javax.swing.JButton();
        dahiliyelButton = new javax.swing.JButton();
        psikolojiButton = new javax.swing.JButton();
        bolumLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fizyolojiButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fizyolojiButton.setText("Fizyoloji");
        fizyolojiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fizyolojiButtonActionPerformed(evt);
            }
        });

        norolojıButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        norolojıButton.setText("Nöroloji");
        norolojıButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                norolojıButtonActionPerformed(evt);
            }
        });

        gozButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        gozButton.setText("Göz Hastalıkları");

        urolojıButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        urolojıButton.setText("Üroloji");
        urolojıButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urolojıButtonActionPerformed(evt);
            }
        });

        dahiliyelButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dahiliyelButton.setText("Dahiliye");
        dahiliyelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dahiliyelButtonActionPerformed(evt);
            }
        });

        psikolojiButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        psikolojiButton.setText("Psikoloji");
        psikolojiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psikolojiButtonActionPerformed(evt);
            }
        });

        bolumLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bolumLabel.setText("Bölüm Seçiniz");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gozButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(urolojıButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dahiliyelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(psikolojiButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fizyolojiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(norolojıButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bolumLabel)
                .addGap(88, 88, 88))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(bolumLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fizyolojiButton, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(norolojıButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(gozButton, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(urolojıButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dahiliyelButton, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(psikolojiButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fizyolojiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fizyolojiButtonActionPerformed
        // TODO add your handling code here:
        Doctor doct = new Doctor();
        doct.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_fizyolojiButtonActionPerformed

    private void norolojıButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_norolojıButtonActionPerformed
        // TODO add your handling code here:
        //fizyolojiButton.setVisible(false);
    }//GEN-LAST:event_norolojıButtonActionPerformed

    private void urolojıButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urolojıButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_urolojıButtonActionPerformed

    private void dahiliyelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dahiliyelButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dahiliyelButtonActionPerformed

    private void psikolojiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psikolojiButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psikolojiButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bolum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bolum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bolum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bolum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bolum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bolumLabel;
    private javax.swing.JButton dahiliyelButton;
    private javax.swing.JButton fizyolojiButton;
    private javax.swing.JButton gozButton;
    private javax.swing.JButton norolojıButton;
    private javax.swing.JButton psikolojiButton;
    private javax.swing.JButton urolojıButton;
    // End of variables declaration//GEN-END:variables

}
